# Generated by Django 4.0.7 on 2022-08-18 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_collation='Turkish_CI_AS', db_column='Name', max_length=255)),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
                'db_table': 'Addresses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_collation='Turkish_CI_AS', max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_collation='Turkish_CI_AS', max_length=255)),
                ('codename', models.CharField(db_collation='Turkish_CI_AS', max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(db_collation='Turkish_CI_AS', max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(db_collation='Turkish_CI_AS', max_length=150, unique=True)),
                ('first_name', models.CharField(db_collation='Turkish_CI_AS', max_length=150)),
                ('last_name', models.CharField(db_collation='Turkish_CI_AS', max_length=150)),
                ('email', models.CharField(db_collation='Turkish_CI_AS', max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Deletedemployers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_id', models.IntegerField(blank=True, db_column='Old_id', null=True)),
                ('lastname', models.CharField(db_collation='Turkish_CI_AS', db_column='LastName', max_length=255)),
                ('firstname', models.CharField(db_collation='Turkish_CI_AS', db_column='FirstName', max_length=255)),
                ('tck', models.CharField(db_collation='Turkish_CI_AS', db_column='TCK', max_length=11, unique=True)),
                ('phonenumber', models.CharField(db_collation='Turkish_CI_AS', db_column='PhoneNumber', max_length=10, unique=True)),
                ('createddate', models.DateTimeField(blank=True, db_column='createdDate', null=True)),
                ('deletedate', models.DateTimeField(blank=True, db_column='deleteDate', null=True)),
            ],
            options={
                'verbose_name': 'Deleted Employer',
                'verbose_name_plural': 'Deleted Employers',
                'db_table': 'DeletedEmployers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, db_collation='Turkish_CI_AS', null=True)),
                ('object_repr', models.CharField(db_collation='Turkish_CI_AS', max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField(db_collation='Turkish_CI_AS')),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(db_collation='Turkish_CI_AS', max_length=100)),
                ('model', models.CharField(db_collation='Turkish_CI_AS', max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(db_collation='Turkish_CI_AS', max_length=255)),
                ('name', models.CharField(db_collation='Turkish_CI_AS', max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(db_collation='Turkish_CI_AS', max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField(db_collation='Turkish_CI_AS')),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(db_collation='Turkish_CI_AS', db_column='LastName', max_length=255)),
                ('firstname', models.CharField(db_collation='Turkish_CI_AS', db_column='FirstName', max_length=255)),
                ('age', models.IntegerField(blank=True, db_column='Age', null=True)),
                ('tck', models.CharField(db_collation='Turkish_CI_AS', db_column='TCK', max_length=11, unique=True)),
                ('photoid', models.CharField(blank=True, db_column='PhotoId', max_length=36, null=True)),
                ('email', models.CharField(blank=True, db_collation='Turkish_CI_AS', db_column='Email', max_length=255, null=True)),
                ('phonenumber', models.CharField(db_collation='Turkish_CI_AS', db_column='PhoneNumber', max_length=10, unique=True)),
                ('createddate', models.DateTimeField(blank=True, db_column='createdDate', null=True)),
                ('updatedate', models.DateTimeField(blank=True, db_column='updateDate', null=True)),
                ('deletedate', models.DateTimeField(blank=True, db_column='deleteDate', null=True)),
            ],
            options={
                'verbose_name': 'Employer',
                'verbose_name_plural': 'Employers',
                'db_table': 'Employers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Entrances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createddate', models.DateTimeField(blank=True, db_column='createdDate', null=True)),
            ],
            options={
                'verbose_name': 'Entrance',
                'verbose_name_plural': 'Entrances',
                'db_table': 'Entrances',
                'managed': False,
            },
        ),
    ]
