# Generated by Django 4.0.7 on 2022-08-23 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deletedworkers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_id', models.IntegerField(blank=True, db_column='Old_id', null=True)),
                ('lastname', models.CharField(db_collation='Turkish_CI_AS', db_column='LastName', max_length=255)),
                ('firstname', models.CharField(db_collation='Turkish_CI_AS', db_column='FirstName', max_length=255)),
                ('tck', models.CharField(db_collation='Turkish_CI_AS', db_column='TCK', max_length=11, unique=True)),
                ('phonenumber', models.CharField(db_collation='Turkish_CI_AS', db_column='PhoneNumber', max_length=10, unique=True)),
                ('createddate', models.DateTimeField(blank=True, db_column='createdDate', null=True)),
                ('deletedate', models.DateTimeField(blank=True, db_column='deleteDate', null=True)),
            ],
            options={
                'verbose_name': 'Deleted Workers',
                'verbose_name_plural': 'Deleted Workers',
                'db_table': 'Deletedworkers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(db_collation='Turkish_CI_AS', db_column='LastName', max_length=255)),
                ('firstname', models.CharField(db_collation='Turkish_CI_AS', db_column='FirstName', max_length=255)),
                ('age', models.IntegerField(blank=True, db_column='Age', null=True)),
                ('tck', models.CharField(db_collation='Turkish_CI_AS', db_column='TCK', max_length=11, unique=True)),
                ('photoid', models.CharField(blank=True, db_column='PhotoId', max_length=36, null=True)),
                ('email', models.CharField(blank=True, db_collation='Turkish_CI_AS', db_column='Email', max_length=255, null=True)),
                ('phonenumber', models.CharField(db_collation='Turkish_CI_AS', db_column='PhoneNumber', max_length=10, unique=True)),
                ('createddate', models.DateTimeField(blank=True, db_column='createdDate', null=True)),
                ('updatedate', models.DateTimeField(blank=True, db_column='updateDate', null=True)),
                ('deletedate', models.DateTimeField(blank=True, db_column='deleteDate', null=True)),
            ],
            options={
                'verbose_name': 'Workers',
                'verbose_name_plural': 'Workers',
                'db_table': 'Workers',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Deletedemployers',
        ),
        migrations.DeleteModel(
            name='Employers',
        ),
    ]
