# Generated by Django 4.0.7 on 2022-08-31 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_deletedworkers_workers_delete_deletedemployers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deneme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(db_collation='Turkish_CI_AS', db_column='LastName', max_length=255)),
            ],
            options={
                'verbose_name': 'Deneme',
                'verbose_name_plural': 'Deneme',
                'db_table': 'Deneme',
                'managed': False,
            },
        ),
    ]
